#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamieDB.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JamieDB")]
	public partial class JamieDBLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIngredientType(IngredientType instance);
    partial void UpdateIngredientType(IngredientType instance);
    partial void DeleteIngredientType(IngredientType instance);
    partial void InsertIngredient(Ingredient instance);
    partial void UpdateIngredient(Ingredient instance);
    partial void DeleteIngredient(Ingredient instance);
    partial void InsertUnitType(UnitType instance);
    partial void UpdateUnitType(UnitType instance);
    partial void DeleteUnitType(UnitType instance);
    partial void InsertRecipeIngredient(RecipeIngredient instance);
    partial void UpdateRecipeIngredient(RecipeIngredient instance);
    partial void DeleteRecipeIngredient(RecipeIngredient instance);
    partial void InsertRecipe(Recipe instance);
    partial void UpdateRecipe(Recipe instance);
    partial void DeleteRecipe(Recipe instance);
    partial void InsertUnit(Unit instance);
    partial void UpdateUnit(Unit instance);
    partial void DeleteUnit(Unit instance);
    partial void InsertUnitTranslation(UnitTranslation instance);
    partial void UpdateUnitTranslation(UnitTranslation instance);
    partial void DeleteUnitTranslation(UnitTranslation instance);
    partial void InsertShoppingList(ShoppingList instance);
    partial void UpdateShoppingList(ShoppingList instance);
    partial void DeleteShoppingList(ShoppingList instance);
    partial void InsertFoodPlanItem(FoodPlanItem instance);
    partial void UpdateFoodPlanItem(FoodPlanItem instance);
    partial void DeleteFoodPlanItem(FoodPlanItem instance);
    partial void InsertShoppingListItem(ShoppingListItem instance);
    partial void UpdateShoppingListItem(ShoppingListItem instance);
    partial void DeleteShoppingListItem(ShoppingListItem instance);
    partial void InsertFoodPlan(FoodPlan instance);
    partial void UpdateFoodPlan(FoodPlan instance);
    partial void DeleteFoodPlan(FoodPlan instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public JamieDBLinqDataContext() : 
				base(global::JamieDB.Properties.Settings.Default.JamieDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public JamieDBLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JamieDBLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JamieDBLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JamieDBLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IngredientType> IngredientTypes
		{
			get
			{
				return this.GetTable<IngredientType>();
			}
		}
		
		public System.Data.Linq.Table<Ingredient> Ingredients
		{
			get
			{
				return this.GetTable<Ingredient>();
			}
		}
		
		public System.Data.Linq.Table<UnitType> UnitTypes
		{
			get
			{
				return this.GetTable<UnitType>();
			}
		}
		
		public System.Data.Linq.Table<RecipeIngredient> RecipeIngredients
		{
			get
			{
				return this.GetTable<RecipeIngredient>();
			}
		}
		
		public System.Data.Linq.Table<Recipe> Recipes
		{
			get
			{
				return this.GetTable<Recipe>();
			}
		}
		
		public System.Data.Linq.Table<Unit> Units
		{
			get
			{
				return this.GetTable<Unit>();
			}
		}
		
		public System.Data.Linq.Table<UnitTranslation> UnitTranslations
		{
			get
			{
				return this.GetTable<UnitTranslation>();
			}
		}
		
		public System.Data.Linq.Table<ShoppingList> ShoppingLists
		{
			get
			{
				return this.GetTable<ShoppingList>();
			}
		}
		
		public System.Data.Linq.Table<FoodPlanItem> FoodPlanItems
		{
			get
			{
				return this.GetTable<FoodPlanItem>();
			}
		}
		
		public System.Data.Linq.Table<ShoppingListItem> ShoppingListItems
		{
			get
			{
				return this.GetTable<ShoppingListItem>();
			}
		}
		
		public System.Data.Linq.Table<FoodPlan> FoodPlans
		{
			get
			{
				return this.GetTable<FoodPlan>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IngredientTypes")]
	public partial class IngredientType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private System.Nullable<long> _TargetUnitType;
		
		private EntitySet<Ingredient> _Ingredients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTargetUnitTypeChanging(System.Nullable<long> value);
    partial void OnTargetUnitTypeChanged();
    #endregion
		
		public IngredientType()
		{
			this._Ingredients = new EntitySet<Ingredient>(new Action<Ingredient>(this.attach_Ingredients), new Action<Ingredient>(this.detach_Ingredients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetUnitType", DbType="BigInt")]
		public System.Nullable<long> TargetUnitType
		{
			get
			{
				return this._TargetUnitType;
			}
			set
			{
				if ((this._TargetUnitType != value))
				{
					this.OnTargetUnitTypeChanging(value);
					this.SendPropertyChanging();
					this._TargetUnitType = value;
					this.SendPropertyChanged("TargetUnitType");
					this.OnTargetUnitTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IngredientType_Ingredient", Storage="_Ingredients", ThisKey="Id", OtherKey="TypeID")]
		public EntitySet<Ingredient> Ingredients
		{
			get
			{
				return this._Ingredients;
			}
			set
			{
				this._Ingredients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ingredients(Ingredient entity)
		{
			this.SendPropertyChanging();
			entity.IngredientType = this;
		}
		
		private void detach_Ingredients(Ingredient entity)
		{
			this.SendPropertyChanging();
			entity.IngredientType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ingredients")]
	public partial class Ingredient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private System.Nullable<long> _TypeID;
		
		private System.Nullable<long> _TargetUnitID;
		
		private System.Nullable<bool> _IsVegan;
		
		private System.Nullable<bool> _IsVegetarian;
		
		private System.Nullable<bool> _IsLowCarb;
		
		private System.Nullable<bool> _IsLowFat;
		
		private EntitySet<RecipeIngredient> _RecipeIngredients;
		
		private EntitySet<UnitTranslation> _UnitTranslations;
		
		private EntitySet<ShoppingListItem> _ShoppingListItems;
		
		private EntityRef<IngredientType> _IngredientType;
		
		private EntityRef<Unit> _Unit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTypeIDChanging(System.Nullable<long> value);
    partial void OnTypeIDChanged();
    partial void OnTargetUnitIDChanging(System.Nullable<long> value);
    partial void OnTargetUnitIDChanged();
    partial void OnIsVeganChanging(System.Nullable<bool> value);
    partial void OnIsVeganChanged();
    partial void OnIsVegetarianChanging(System.Nullable<bool> value);
    partial void OnIsVegetarianChanged();
    partial void OnIsLowCarbChanging(System.Nullable<bool> value);
    partial void OnIsLowCarbChanged();
    partial void OnIsLowFatChanging(System.Nullable<bool> value);
    partial void OnIsLowFatChanged();
    #endregion
		
		public Ingredient()
		{
			this._RecipeIngredients = new EntitySet<RecipeIngredient>(new Action<RecipeIngredient>(this.attach_RecipeIngredients), new Action<RecipeIngredient>(this.detach_RecipeIngredients));
			this._UnitTranslations = new EntitySet<UnitTranslation>(new Action<UnitTranslation>(this.attach_UnitTranslations), new Action<UnitTranslation>(this.detach_UnitTranslations));
			this._ShoppingListItems = new EntitySet<ShoppingListItem>(new Action<ShoppingListItem>(this.attach_ShoppingListItems), new Action<ShoppingListItem>(this.detach_ShoppingListItems));
			this._IngredientType = default(EntityRef<IngredientType>);
			this._Unit = default(EntityRef<Unit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="BigInt")]
		public System.Nullable<long> TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					if (this._IngredientType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TypeID = value;
					this.SendPropertyChanged("TypeID");
					this.OnTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetUnitID", DbType="BigInt")]
		public System.Nullable<long> TargetUnitID
		{
			get
			{
				return this._TargetUnitID;
			}
			set
			{
				if ((this._TargetUnitID != value))
				{
					if (this._Unit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTargetUnitIDChanging(value);
					this.SendPropertyChanging();
					this._TargetUnitID = value;
					this.SendPropertyChanged("TargetUnitID");
					this.OnTargetUnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVegan", DbType="Bit")]
		public System.Nullable<bool> IsVegan
		{
			get
			{
				return this._IsVegan;
			}
			set
			{
				if ((this._IsVegan != value))
				{
					this.OnIsVeganChanging(value);
					this.SendPropertyChanging();
					this._IsVegan = value;
					this.SendPropertyChanged("IsVegan");
					this.OnIsVeganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVegetarian", DbType="Bit")]
		public System.Nullable<bool> IsVegetarian
		{
			get
			{
				return this._IsVegetarian;
			}
			set
			{
				if ((this._IsVegetarian != value))
				{
					this.OnIsVegetarianChanging(value);
					this.SendPropertyChanging();
					this._IsVegetarian = value;
					this.SendPropertyChanged("IsVegetarian");
					this.OnIsVegetarianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLowCarb", DbType="Bit")]
		public System.Nullable<bool> IsLowCarb
		{
			get
			{
				return this._IsLowCarb;
			}
			set
			{
				if ((this._IsLowCarb != value))
				{
					this.OnIsLowCarbChanging(value);
					this.SendPropertyChanging();
					this._IsLowCarb = value;
					this.SendPropertyChanged("IsLowCarb");
					this.OnIsLowCarbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLowFat", DbType="Bit")]
		public System.Nullable<bool> IsLowFat
		{
			get
			{
				return this._IsLowFat;
			}
			set
			{
				if ((this._IsLowFat != value))
				{
					this.OnIsLowFatChanging(value);
					this.SendPropertyChanging();
					this._IsLowFat = value;
					this.SendPropertyChanged("IsLowFat");
					this.OnIsLowFatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_RecipeIngredient", Storage="_RecipeIngredients", ThisKey="Id", OtherKey="IngredientID")]
		public EntitySet<RecipeIngredient> RecipeIngredients
		{
			get
			{
				return this._RecipeIngredients;
			}
			set
			{
				this._RecipeIngredients.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_UnitTranslation", Storage="_UnitTranslations", ThisKey="Id", OtherKey="AffectedIngredientID")]
		public EntitySet<UnitTranslation> UnitTranslations
		{
			get
			{
				return this._UnitTranslations;
			}
			set
			{
				this._UnitTranslations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_ShoppingListItem", Storage="_ShoppingListItems", ThisKey="Id", OtherKey="IngredientID")]
		public EntitySet<ShoppingListItem> ShoppingListItems
		{
			get
			{
				return this._ShoppingListItems;
			}
			set
			{
				this._ShoppingListItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IngredientType_Ingredient", Storage="_IngredientType", ThisKey="TypeID", OtherKey="Id", IsForeignKey=true)]
		public IngredientType IngredientType
		{
			get
			{
				return this._IngredientType.Entity;
			}
			set
			{
				IngredientType previousValue = this._IngredientType.Entity;
				if (((previousValue != value) 
							|| (this._IngredientType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._IngredientType.Entity = null;
						previousValue.Ingredients.Remove(this);
					}
					this._IngredientType.Entity = value;
					if ((value != null))
					{
						value.Ingredients.Add(this);
						this._TypeID = value.Id;
					}
					else
					{
						this._TypeID = default(Nullable<long>);
					}
					this.SendPropertyChanged("IngredientType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_Ingredient", Storage="_Unit", ThisKey="TargetUnitID", OtherKey="Id", IsForeignKey=true)]
		public Unit Unit
		{
			get
			{
				return this._Unit.Entity;
			}
			set
			{
				Unit previousValue = this._Unit.Entity;
				if (((previousValue != value) 
							|| (this._Unit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Unit.Entity = null;
						previousValue.Ingredients.Remove(this);
					}
					this._Unit.Entity = value;
					if ((value != null))
					{
						value.Ingredients.Add(this);
						this._TargetUnitID = value.Id;
					}
					else
					{
						this._TargetUnitID = default(Nullable<long>);
					}
					this.SendPropertyChanged("Unit");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RecipeIngredients(RecipeIngredient entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = this;
		}
		
		private void detach_RecipeIngredients(RecipeIngredient entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = null;
		}
		
		private void attach_UnitTranslations(UnitTranslation entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = this;
		}
		
		private void detach_UnitTranslations(UnitTranslation entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = null;
		}
		
		private void attach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = this;
		}
		
		private void detach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnitTypes")]
	public partial class UnitType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private long _StandardUnit;
		
		private EntitySet<Unit> _Units;
		
		private EntityRef<Unit> _Unit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnStandardUnitChanging(long value);
    partial void OnStandardUnitChanged();
    #endregion
		
		public UnitType()
		{
			this._Units = new EntitySet<Unit>(new Action<Unit>(this.attach_Units), new Action<Unit>(this.detach_Units));
			this._Unit = default(EntityRef<Unit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardUnit", DbType="BigInt NOT NULL")]
		public long StandardUnit
		{
			get
			{
				return this._StandardUnit;
			}
			set
			{
				if ((this._StandardUnit != value))
				{
					if (this._Unit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStandardUnitChanging(value);
					this.SendPropertyChanging();
					this._StandardUnit = value;
					this.SendPropertyChanged("StandardUnit");
					this.OnStandardUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UnitType_Unit", Storage="_Units", ThisKey="Id", OtherKey="TypeID")]
		public EntitySet<Unit> Units
		{
			get
			{
				return this._Units;
			}
			set
			{
				this._Units.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_UnitType", Storage="_Unit", ThisKey="StandardUnit", OtherKey="Id", IsForeignKey=true)]
		public Unit Unit
		{
			get
			{
				return this._Unit.Entity;
			}
			set
			{
				Unit previousValue = this._Unit.Entity;
				if (((previousValue != value) 
							|| (this._Unit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Unit.Entity = null;
						previousValue.UnitTypes.Remove(this);
					}
					this._Unit.Entity = value;
					if ((value != null))
					{
						value.UnitTypes.Add(this);
						this._StandardUnit = value.Id;
					}
					else
					{
						this._StandardUnit = default(long);
					}
					this.SendPropertyChanged("Unit");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Units(Unit entity)
		{
			this.SendPropertyChanging();
			entity.UnitType = this;
		}
		
		private void detach_Units(Unit entity)
		{
			this.SendPropertyChanging();
			entity.UnitType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecipeIngredients")]
	public partial class RecipeIngredient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _RecipeID;
		
		private long _IngredientID;
		
		private double _Quantity;
		
		private long _UnitID;
		
		private EntitySet<ShoppingListItem> _ShoppingListItems;
		
		private EntityRef<Ingredient> _Ingredient;
		
		private EntityRef<Recipe> _Recipe;
		
		private EntityRef<Unit> _Unit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnRecipeIDChanging(long value);
    partial void OnRecipeIDChanged();
    partial void OnIngredientIDChanging(long value);
    partial void OnIngredientIDChanged();
    partial void OnQuantityChanging(double value);
    partial void OnQuantityChanged();
    partial void OnUnitIDChanging(long value);
    partial void OnUnitIDChanged();
    #endregion
		
		public RecipeIngredient()
		{
			this._ShoppingListItems = new EntitySet<ShoppingListItem>(new Action<ShoppingListItem>(this.attach_ShoppingListItems), new Action<ShoppingListItem>(this.detach_ShoppingListItems));
			this._Ingredient = default(EntityRef<Ingredient>);
			this._Recipe = default(EntityRef<Recipe>);
			this._Unit = default(EntityRef<Unit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="BigInt NOT NULL")]
		public long RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					if (this._Recipe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRecipeIDChanging(value);
					this.SendPropertyChanging();
					this._RecipeID = value;
					this.SendPropertyChanged("RecipeID");
					this.OnRecipeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientID", DbType="BigInt NOT NULL")]
		public long IngredientID
		{
			get
			{
				return this._IngredientID;
			}
			set
			{
				if ((this._IngredientID != value))
				{
					if (this._Ingredient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIngredientIDChanging(value);
					this.SendPropertyChanging();
					this._IngredientID = value;
					this.SendPropertyChanged("IngredientID");
					this.OnIngredientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float NOT NULL")]
		public double Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitID", DbType="BigInt NOT NULL")]
		public long UnitID
		{
			get
			{
				return this._UnitID;
			}
			set
			{
				if ((this._UnitID != value))
				{
					if (this._Unit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUnitIDChanging(value);
					this.SendPropertyChanging();
					this._UnitID = value;
					this.SendPropertyChanged("UnitID");
					this.OnUnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RecipeIngredient_ShoppingListItem", Storage="_ShoppingListItems", ThisKey="Id", OtherKey="RecipeIngredientID")]
		public EntitySet<ShoppingListItem> ShoppingListItems
		{
			get
			{
				return this._ShoppingListItems;
			}
			set
			{
				this._ShoppingListItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_RecipeIngredient", Storage="_Ingredient", ThisKey="IngredientID", OtherKey="Id", IsForeignKey=true)]
		public Ingredient Ingredient
		{
			get
			{
				return this._Ingredient.Entity;
			}
			set
			{
				Ingredient previousValue = this._Ingredient.Entity;
				if (((previousValue != value) 
							|| (this._Ingredient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ingredient.Entity = null;
						previousValue.RecipeIngredients.Remove(this);
					}
					this._Ingredient.Entity = value;
					if ((value != null))
					{
						value.RecipeIngredients.Add(this);
						this._IngredientID = value.Id;
					}
					else
					{
						this._IngredientID = default(long);
					}
					this.SendPropertyChanged("Ingredient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recipe_RecipeIngredient", Storage="_Recipe", ThisKey="RecipeID", OtherKey="Id", IsForeignKey=true)]
		public Recipe Recipe
		{
			get
			{
				return this._Recipe.Entity;
			}
			set
			{
				Recipe previousValue = this._Recipe.Entity;
				if (((previousValue != value) 
							|| (this._Recipe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Recipe.Entity = null;
						previousValue.RecipeIngredients.Remove(this);
					}
					this._Recipe.Entity = value;
					if ((value != null))
					{
						value.RecipeIngredients.Add(this);
						this._RecipeID = value.Id;
					}
					else
					{
						this._RecipeID = default(long);
					}
					this.SendPropertyChanged("Recipe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_RecipeIngredient", Storage="_Unit", ThisKey="UnitID", OtherKey="Id", IsForeignKey=true)]
		public Unit Unit
		{
			get
			{
				return this._Unit.Entity;
			}
			set
			{
				Unit previousValue = this._Unit.Entity;
				if (((previousValue != value) 
							|| (this._Unit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Unit.Entity = null;
						previousValue.RecipeIngredients.Remove(this);
					}
					this._Unit.Entity = value;
					if ((value != null))
					{
						value.RecipeIngredients.Add(this);
						this._UnitID = value.Id;
					}
					else
					{
						this._UnitID = default(long);
					}
					this.SendPropertyChanged("Unit");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.RecipeIngredient = this;
		}
		
		private void detach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.RecipeIngredient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recipes")]
	public partial class Recipe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private double _PortionQuantity;
		
		private string _Source;
		
		private System.Nullable<int> _SourcePage;
		
		private string _SourceISBN;
		
		private string _Summary;
		
		private EntitySet<RecipeIngredient> _RecipeIngredients;
		
		private EntitySet<FoodPlanItem> _FoodPlanItems;
		
		private EntitySet<ShoppingListItem> _ShoppingListItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPortionQuantityChanging(double value);
    partial void OnPortionQuantityChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnSourcePageChanging(System.Nullable<int> value);
    partial void OnSourcePageChanged();
    partial void OnSourceISBNChanging(string value);
    partial void OnSourceISBNChanged();
    partial void OnSummaryChanging(string value);
    partial void OnSummaryChanged();
    #endregion
		
		public Recipe()
		{
			this._RecipeIngredients = new EntitySet<RecipeIngredient>(new Action<RecipeIngredient>(this.attach_RecipeIngredients), new Action<RecipeIngredient>(this.detach_RecipeIngredients));
			this._FoodPlanItems = new EntitySet<FoodPlanItem>(new Action<FoodPlanItem>(this.attach_FoodPlanItems), new Action<FoodPlanItem>(this.detach_FoodPlanItems));
			this._ShoppingListItems = new EntitySet<ShoppingListItem>(new Action<ShoppingListItem>(this.attach_ShoppingListItems), new Action<ShoppingListItem>(this.detach_ShoppingListItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortionQuantity", DbType="Float NOT NULL")]
		public double PortionQuantity
		{
			get
			{
				return this._PortionQuantity;
			}
			set
			{
				if ((this._PortionQuantity != value))
				{
					this.OnPortionQuantityChanging(value);
					this.SendPropertyChanging();
					this._PortionQuantity = value;
					this.SendPropertyChanged("PortionQuantity");
					this.OnPortionQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourcePage", DbType="Int")]
		public System.Nullable<int> SourcePage
		{
			get
			{
				return this._SourcePage;
			}
			set
			{
				if ((this._SourcePage != value))
				{
					this.OnSourcePageChanging(value);
					this.SendPropertyChanging();
					this._SourcePage = value;
					this.SendPropertyChanged("SourcePage");
					this.OnSourcePageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceISBN", DbType="NChar(10)")]
		public string SourceISBN
		{
			get
			{
				return this._SourceISBN;
			}
			set
			{
				if ((this._SourceISBN != value))
				{
					this.OnSourceISBNChanging(value);
					this.SendPropertyChanging();
					this._SourceISBN = value;
					this.SendPropertyChanged("SourceISBN");
					this.OnSourceISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summary", DbType="NVarChar(50)")]
		public string Summary
		{
			get
			{
				return this._Summary;
			}
			set
			{
				if ((this._Summary != value))
				{
					this.OnSummaryChanging(value);
					this.SendPropertyChanging();
					this._Summary = value;
					this.SendPropertyChanged("Summary");
					this.OnSummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recipe_RecipeIngredient", Storage="_RecipeIngredients", ThisKey="Id", OtherKey="RecipeID")]
		public EntitySet<RecipeIngredient> RecipeIngredients
		{
			get
			{
				return this._RecipeIngredients;
			}
			set
			{
				this._RecipeIngredients.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recipe_FoodPlanItem", Storage="_FoodPlanItems", ThisKey="Id", OtherKey="RecipeID")]
		public EntitySet<FoodPlanItem> FoodPlanItems
		{
			get
			{
				return this._FoodPlanItems;
			}
			set
			{
				this._FoodPlanItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recipe_ShoppingListItem", Storage="_ShoppingListItems", ThisKey="Id", OtherKey="RecipeID")]
		public EntitySet<ShoppingListItem> ShoppingListItems
		{
			get
			{
				return this._ShoppingListItems;
			}
			set
			{
				this._ShoppingListItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RecipeIngredients(RecipeIngredient entity)
		{
			this.SendPropertyChanging();
			entity.Recipe = this;
		}
		
		private void detach_RecipeIngredients(RecipeIngredient entity)
		{
			this.SendPropertyChanging();
			entity.Recipe = null;
		}
		
		private void attach_FoodPlanItems(FoodPlanItem entity)
		{
			this.SendPropertyChanging();
			entity.Recipe = this;
		}
		
		private void detach_FoodPlanItems(FoodPlanItem entity)
		{
			this.SendPropertyChanging();
			entity.Recipe = null;
		}
		
		private void attach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.Recipe = this;
		}
		
		private void detach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.Recipe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Units")]
	public partial class Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Symbol;
		
		private string _Name;
		
		private long _TypeID;
		
		private bool _TypeStandard;
		
		private System.Nullable<double> _TypeFactor;
		
		private bool _TypeUniversal;
		
		private EntitySet<Ingredient> _Ingredients;
		
		private EntitySet<UnitType> _UnitTypes;
		
		private EntitySet<RecipeIngredient> _RecipeIngredients;
		
		private EntitySet<UnitTranslation> _UnitTranslations;
		
		private EntitySet<UnitTranslation> _UnitTranslations1;
		
		private EntityRef<UnitType> _UnitType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnSymbolChanging(string value);
    partial void OnSymbolChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTypeIDChanging(long value);
    partial void OnTypeIDChanged();
    partial void OnTypeStandardChanging(bool value);
    partial void OnTypeStandardChanged();
    partial void OnTypeFactorChanging(System.Nullable<double> value);
    partial void OnTypeFactorChanged();
    partial void OnTypeUniversalChanging(bool value);
    partial void OnTypeUniversalChanged();
    #endregion
		
		public Unit()
		{
			this._Ingredients = new EntitySet<Ingredient>(new Action<Ingredient>(this.attach_Ingredients), new Action<Ingredient>(this.detach_Ingredients));
			this._UnitTypes = new EntitySet<UnitType>(new Action<UnitType>(this.attach_UnitTypes), new Action<UnitType>(this.detach_UnitTypes));
			this._RecipeIngredients = new EntitySet<RecipeIngredient>(new Action<RecipeIngredient>(this.attach_RecipeIngredients), new Action<RecipeIngredient>(this.detach_RecipeIngredients));
			this._UnitTranslations = new EntitySet<UnitTranslation>(new Action<UnitTranslation>(this.attach_UnitTranslations), new Action<UnitTranslation>(this.detach_UnitTranslations));
			this._UnitTranslations1 = new EntitySet<UnitTranslation>(new Action<UnitTranslation>(this.attach_UnitTranslations1), new Action<UnitTranslation>(this.detach_UnitTranslations1));
			this._UnitType = default(EntityRef<UnitType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="BigInt NOT NULL")]
		public long TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					if (this._UnitType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TypeID = value;
					this.SendPropertyChanged("TypeID");
					this.OnTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeStandard", DbType="Bit NOT NULL")]
		public bool TypeStandard
		{
			get
			{
				return this._TypeStandard;
			}
			set
			{
				if ((this._TypeStandard != value))
				{
					this.OnTypeStandardChanging(value);
					this.SendPropertyChanging();
					this._TypeStandard = value;
					this.SendPropertyChanged("TypeStandard");
					this.OnTypeStandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeFactor", DbType="Float")]
		public System.Nullable<double> TypeFactor
		{
			get
			{
				return this._TypeFactor;
			}
			set
			{
				if ((this._TypeFactor != value))
				{
					this.OnTypeFactorChanging(value);
					this.SendPropertyChanging();
					this._TypeFactor = value;
					this.SendPropertyChanged("TypeFactor");
					this.OnTypeFactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeUniversal", DbType="Bit NOT NULL")]
		public bool TypeUniversal
		{
			get
			{
				return this._TypeUniversal;
			}
			set
			{
				if ((this._TypeUniversal != value))
				{
					this.OnTypeUniversalChanging(value);
					this.SendPropertyChanging();
					this._TypeUniversal = value;
					this.SendPropertyChanged("TypeUniversal");
					this.OnTypeUniversalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_Ingredient", Storage="_Ingredients", ThisKey="Id", OtherKey="TargetUnitID")]
		public EntitySet<Ingredient> Ingredients
		{
			get
			{
				return this._Ingredients;
			}
			set
			{
				this._Ingredients.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_UnitType", Storage="_UnitTypes", ThisKey="Id", OtherKey="StandardUnit")]
		public EntitySet<UnitType> UnitTypes
		{
			get
			{
				return this._UnitTypes;
			}
			set
			{
				this._UnitTypes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_RecipeIngredient", Storage="_RecipeIngredients", ThisKey="Id", OtherKey="UnitID")]
		public EntitySet<RecipeIngredient> RecipeIngredients
		{
			get
			{
				return this._RecipeIngredients;
			}
			set
			{
				this._RecipeIngredients.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_UnitTranslation", Storage="_UnitTranslations", ThisKey="Id", OtherKey="BaseUnitID")]
		public EntitySet<UnitTranslation> UnitTranslations
		{
			get
			{
				return this._UnitTranslations;
			}
			set
			{
				this._UnitTranslations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_UnitTranslation1", Storage="_UnitTranslations1", ThisKey="Id", OtherKey="TargetUnitID")]
		public EntitySet<UnitTranslation> UnitTranslations1
		{
			get
			{
				return this._UnitTranslations1;
			}
			set
			{
				this._UnitTranslations1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UnitType_Unit", Storage="_UnitType", ThisKey="TypeID", OtherKey="Id", IsForeignKey=true)]
		public UnitType UnitType
		{
			get
			{
				return this._UnitType.Entity;
			}
			set
			{
				UnitType previousValue = this._UnitType.Entity;
				if (((previousValue != value) 
							|| (this._UnitType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UnitType.Entity = null;
						previousValue.Units.Remove(this);
					}
					this._UnitType.Entity = value;
					if ((value != null))
					{
						value.Units.Add(this);
						this._TypeID = value.Id;
					}
					else
					{
						this._TypeID = default(long);
					}
					this.SendPropertyChanged("UnitType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ingredients(Ingredient entity)
		{
			this.SendPropertyChanging();
			entity.Unit = this;
		}
		
		private void detach_Ingredients(Ingredient entity)
		{
			this.SendPropertyChanging();
			entity.Unit = null;
		}
		
		private void attach_UnitTypes(UnitType entity)
		{
			this.SendPropertyChanging();
			entity.Unit = this;
		}
		
		private void detach_UnitTypes(UnitType entity)
		{
			this.SendPropertyChanging();
			entity.Unit = null;
		}
		
		private void attach_RecipeIngredients(RecipeIngredient entity)
		{
			this.SendPropertyChanging();
			entity.Unit = this;
		}
		
		private void detach_RecipeIngredients(RecipeIngredient entity)
		{
			this.SendPropertyChanging();
			entity.Unit = null;
		}
		
		private void attach_UnitTranslations(UnitTranslation entity)
		{
			this.SendPropertyChanging();
			entity.Unit = this;
		}
		
		private void detach_UnitTranslations(UnitTranslation entity)
		{
			this.SendPropertyChanging();
			entity.Unit = null;
		}
		
		private void attach_UnitTranslations1(UnitTranslation entity)
		{
			this.SendPropertyChanging();
			entity.Unit1 = this;
		}
		
		private void detach_UnitTranslations1(UnitTranslation entity)
		{
			this.SendPropertyChanging();
			entity.Unit1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnitTranslations")]
	public partial class UnitTranslation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _AffectedIngredientID;
		
		private long _BaseUnitID;
		
		private long _TargetUnitID;
		
		private double _Factor;
		
		private EntityRef<Unit> _Unit;
		
		private EntityRef<Ingredient> _Ingredient;
		
		private EntityRef<Unit> _Unit1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnAffectedIngredientIDChanging(long value);
    partial void OnAffectedIngredientIDChanged();
    partial void OnBaseUnitIDChanging(long value);
    partial void OnBaseUnitIDChanged();
    partial void OnTargetUnitIDChanging(long value);
    partial void OnTargetUnitIDChanged();
    partial void OnFactorChanging(double value);
    partial void OnFactorChanged();
    #endregion
		
		public UnitTranslation()
		{
			this._Unit = default(EntityRef<Unit>);
			this._Ingredient = default(EntityRef<Ingredient>);
			this._Unit1 = default(EntityRef<Unit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AffectedIngredientID", DbType="BigInt NOT NULL")]
		public long AffectedIngredientID
		{
			get
			{
				return this._AffectedIngredientID;
			}
			set
			{
				if ((this._AffectedIngredientID != value))
				{
					if (this._Ingredient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAffectedIngredientIDChanging(value);
					this.SendPropertyChanging();
					this._AffectedIngredientID = value;
					this.SendPropertyChanged("AffectedIngredientID");
					this.OnAffectedIngredientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseUnitID", DbType="BigInt NOT NULL")]
		public long BaseUnitID
		{
			get
			{
				return this._BaseUnitID;
			}
			set
			{
				if ((this._BaseUnitID != value))
				{
					if (this._Unit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBaseUnitIDChanging(value);
					this.SendPropertyChanging();
					this._BaseUnitID = value;
					this.SendPropertyChanged("BaseUnitID");
					this.OnBaseUnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetUnitID", DbType="BigInt NOT NULL")]
		public long TargetUnitID
		{
			get
			{
				return this._TargetUnitID;
			}
			set
			{
				if ((this._TargetUnitID != value))
				{
					if (this._Unit1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTargetUnitIDChanging(value);
					this.SendPropertyChanging();
					this._TargetUnitID = value;
					this.SendPropertyChanged("TargetUnitID");
					this.OnTargetUnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Factor", DbType="Float NOT NULL")]
		public double Factor
		{
			get
			{
				return this._Factor;
			}
			set
			{
				if ((this._Factor != value))
				{
					this.OnFactorChanging(value);
					this.SendPropertyChanging();
					this._Factor = value;
					this.SendPropertyChanged("Factor");
					this.OnFactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_UnitTranslation", Storage="_Unit", ThisKey="BaseUnitID", OtherKey="Id", IsForeignKey=true)]
		public Unit Unit
		{
			get
			{
				return this._Unit.Entity;
			}
			set
			{
				Unit previousValue = this._Unit.Entity;
				if (((previousValue != value) 
							|| (this._Unit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Unit.Entity = null;
						previousValue.UnitTranslations.Remove(this);
					}
					this._Unit.Entity = value;
					if ((value != null))
					{
						value.UnitTranslations.Add(this);
						this._BaseUnitID = value.Id;
					}
					else
					{
						this._BaseUnitID = default(long);
					}
					this.SendPropertyChanged("Unit");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_UnitTranslation", Storage="_Ingredient", ThisKey="AffectedIngredientID", OtherKey="Id", IsForeignKey=true)]
		public Ingredient Ingredient
		{
			get
			{
				return this._Ingredient.Entity;
			}
			set
			{
				Ingredient previousValue = this._Ingredient.Entity;
				if (((previousValue != value) 
							|| (this._Ingredient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ingredient.Entity = null;
						previousValue.UnitTranslations.Remove(this);
					}
					this._Ingredient.Entity = value;
					if ((value != null))
					{
						value.UnitTranslations.Add(this);
						this._AffectedIngredientID = value.Id;
					}
					else
					{
						this._AffectedIngredientID = default(long);
					}
					this.SendPropertyChanged("Ingredient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unit_UnitTranslation1", Storage="_Unit1", ThisKey="TargetUnitID", OtherKey="Id", IsForeignKey=true)]
		public Unit Unit1
		{
			get
			{
				return this._Unit1.Entity;
			}
			set
			{
				Unit previousValue = this._Unit1.Entity;
				if (((previousValue != value) 
							|| (this._Unit1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Unit1.Entity = null;
						previousValue.UnitTranslations1.Remove(this);
					}
					this._Unit1.Entity = value;
					if ((value != null))
					{
						value.UnitTranslations1.Add(this);
						this._TargetUnitID = value.Id;
					}
					else
					{
						this._TargetUnitID = default(long);
					}
					this.SendPropertyChanged("Unit1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShoppingLists")]
	public partial class ShoppingList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private System.Nullable<long> _FoodPlanID;
		
		private System.DateTime _LastModified;
		
		private System.DateTime _FoodplanStartDate;
		
		private System.DateTime _FoodplanEndDate;
		
		private EntitySet<ShoppingListItem> _ShoppingListItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFoodPlanIDChanging(System.Nullable<long> value);
    partial void OnFoodPlanIDChanged();
    partial void OnLastModifiedChanging(System.DateTime value);
    partial void OnLastModifiedChanged();
    partial void OnFoodplanStartDateChanging(System.DateTime value);
    partial void OnFoodplanStartDateChanged();
    partial void OnFoodplanEndDateChanging(System.DateTime value);
    partial void OnFoodplanEndDateChanged();
    #endregion
		
		public ShoppingList()
		{
			this._ShoppingListItems = new EntitySet<ShoppingListItem>(new Action<ShoppingListItem>(this.attach_ShoppingListItems), new Action<ShoppingListItem>(this.detach_ShoppingListItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodPlanID", DbType="BigInt")]
		public System.Nullable<long> FoodPlanID
		{
			get
			{
				return this._FoodPlanID;
			}
			set
			{
				if ((this._FoodPlanID != value))
				{
					this.OnFoodPlanIDChanging(value);
					this.SendPropertyChanging();
					this._FoodPlanID = value;
					this.SendPropertyChanged("FoodPlanID");
					this.OnFoodPlanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModified", DbType="DateTime NOT NULL")]
		public System.DateTime LastModified
		{
			get
			{
				return this._LastModified;
			}
			set
			{
				if ((this._LastModified != value))
				{
					this.OnLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._LastModified = value;
					this.SendPropertyChanged("LastModified");
					this.OnLastModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodplanStartDate", DbType="DateTime NOT NULL")]
		public System.DateTime FoodplanStartDate
		{
			get
			{
				return this._FoodplanStartDate;
			}
			set
			{
				if ((this._FoodplanStartDate != value))
				{
					this.OnFoodplanStartDateChanging(value);
					this.SendPropertyChanging();
					this._FoodplanStartDate = value;
					this.SendPropertyChanged("FoodplanStartDate");
					this.OnFoodplanStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodplanEndDate", DbType="DateTime NOT NULL")]
		public System.DateTime FoodplanEndDate
		{
			get
			{
				return this._FoodplanEndDate;
			}
			set
			{
				if ((this._FoodplanEndDate != value))
				{
					this.OnFoodplanEndDateChanging(value);
					this.SendPropertyChanging();
					this._FoodplanEndDate = value;
					this.SendPropertyChanged("FoodplanEndDate");
					this.OnFoodplanEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShoppingList_ShoppingListItem", Storage="_ShoppingListItems", ThisKey="Id", OtherKey="ShoppingListID")]
		public EntitySet<ShoppingListItem> ShoppingListItems
		{
			get
			{
				return this._ShoppingListItems;
			}
			set
			{
				this._ShoppingListItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.ShoppingList = this;
		}
		
		private void detach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.ShoppingList = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FoodPlanItems")]
	public partial class FoodPlanItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _FoodPlanID;
		
		private System.DateTime _DateTime;
		
		private System.Nullable<double> _PortionCount;
		
		private long _RecipeID;
		
		private EntitySet<ShoppingListItem> _ShoppingListItems;
		
		private EntityRef<Recipe> _Recipe;
		
		private EntityRef<FoodPlan> _FoodPlan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnFoodPlanIDChanging(long value);
    partial void OnFoodPlanIDChanged();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnPortionCountChanging(System.Nullable<double> value);
    partial void OnPortionCountChanged();
    partial void OnRecipeIDChanging(long value);
    partial void OnRecipeIDChanged();
    #endregion
		
		public FoodPlanItem()
		{
			this._ShoppingListItems = new EntitySet<ShoppingListItem>(new Action<ShoppingListItem>(this.attach_ShoppingListItems), new Action<ShoppingListItem>(this.detach_ShoppingListItems));
			this._Recipe = default(EntityRef<Recipe>);
			this._FoodPlan = default(EntityRef<FoodPlan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodPlanID", DbType="BigInt NOT NULL")]
		public long FoodPlanID
		{
			get
			{
				return this._FoodPlanID;
			}
			set
			{
				if ((this._FoodPlanID != value))
				{
					if (this._FoodPlan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodPlanIDChanging(value);
					this.SendPropertyChanging();
					this._FoodPlanID = value;
					this.SendPropertyChanged("FoodPlanID");
					this.OnFoodPlanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL")]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortionCount", DbType="Float")]
		public System.Nullable<double> PortionCount
		{
			get
			{
				return this._PortionCount;
			}
			set
			{
				if ((this._PortionCount != value))
				{
					this.OnPortionCountChanging(value);
					this.SendPropertyChanging();
					this._PortionCount = value;
					this.SendPropertyChanged("PortionCount");
					this.OnPortionCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="BigInt NOT NULL")]
		public long RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					if (this._Recipe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRecipeIDChanging(value);
					this.SendPropertyChanging();
					this._RecipeID = value;
					this.SendPropertyChanged("RecipeID");
					this.OnRecipeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodPlanItem_ShoppingListItem", Storage="_ShoppingListItems", ThisKey="Id", OtherKey="FoodPlanItemID")]
		public EntitySet<ShoppingListItem> ShoppingListItems
		{
			get
			{
				return this._ShoppingListItems;
			}
			set
			{
				this._ShoppingListItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recipe_FoodPlanItem", Storage="_Recipe", ThisKey="RecipeID", OtherKey="Id", IsForeignKey=true)]
		public Recipe Recipe
		{
			get
			{
				return this._Recipe.Entity;
			}
			set
			{
				Recipe previousValue = this._Recipe.Entity;
				if (((previousValue != value) 
							|| (this._Recipe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Recipe.Entity = null;
						previousValue.FoodPlanItems.Remove(this);
					}
					this._Recipe.Entity = value;
					if ((value != null))
					{
						value.FoodPlanItems.Add(this);
						this._RecipeID = value.Id;
					}
					else
					{
						this._RecipeID = default(long);
					}
					this.SendPropertyChanged("Recipe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodPlan_FoodPlanItem", Storage="_FoodPlan", ThisKey="FoodPlanID", OtherKey="Id", IsForeignKey=true)]
		public FoodPlan FoodPlan
		{
			get
			{
				return this._FoodPlan.Entity;
			}
			set
			{
				FoodPlan previousValue = this._FoodPlan.Entity;
				if (((previousValue != value) 
							|| (this._FoodPlan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FoodPlan.Entity = null;
						previousValue.FoodPlanItems.Remove(this);
					}
					this._FoodPlan.Entity = value;
					if ((value != null))
					{
						value.FoodPlanItems.Add(this);
						this._FoodPlanID = value.Id;
					}
					else
					{
						this._FoodPlanID = default(long);
					}
					this.SendPropertyChanged("FoodPlan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.FoodPlanItem = this;
		}
		
		private void detach_ShoppingListItems(ShoppingListItem entity)
		{
			this.SendPropertyChanging();
			entity.FoodPlanItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShoppingListItems")]
	public partial class ShoppingListItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private long _ShoppingListID;
		
		private long _FoodPlanItemID;
		
		private long _RecipeID;
		
		private long _RecipeIngredientID;
		
		private long _IngredientID;
		
		private System.Nullable<double> _TargetUnitQuantity;
		
		private EntityRef<FoodPlanItem> _FoodPlanItem;
		
		private EntityRef<Ingredient> _Ingredient;
		
		private EntityRef<RecipeIngredient> _RecipeIngredient;
		
		private EntityRef<Recipe> _Recipe;
		
		private EntityRef<ShoppingList> _ShoppingList;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnShoppingListIDChanging(long value);
    partial void OnShoppingListIDChanged();
    partial void OnFoodPlanItemIDChanging(long value);
    partial void OnFoodPlanItemIDChanged();
    partial void OnRecipeIDChanging(long value);
    partial void OnRecipeIDChanged();
    partial void OnRecipeIngredientIDChanging(long value);
    partial void OnRecipeIngredientIDChanged();
    partial void OnIngredientIDChanging(long value);
    partial void OnIngredientIDChanged();
    partial void OnTargetUnitQuantityChanging(System.Nullable<double> value);
    partial void OnTargetUnitQuantityChanged();
    #endregion
		
		public ShoppingListItem()
		{
			this._FoodPlanItem = default(EntityRef<FoodPlanItem>);
			this._Ingredient = default(EntityRef<Ingredient>);
			this._RecipeIngredient = default(EntityRef<RecipeIngredient>);
			this._Recipe = default(EntityRef<Recipe>);
			this._ShoppingList = default(EntityRef<ShoppingList>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoppingListID", DbType="BigInt NOT NULL")]
		public long ShoppingListID
		{
			get
			{
				return this._ShoppingListID;
			}
			set
			{
				if ((this._ShoppingListID != value))
				{
					if (this._ShoppingList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShoppingListIDChanging(value);
					this.SendPropertyChanging();
					this._ShoppingListID = value;
					this.SendPropertyChanged("ShoppingListID");
					this.OnShoppingListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodPlanItemID", DbType="BigInt NOT NULL")]
		public long FoodPlanItemID
		{
			get
			{
				return this._FoodPlanItemID;
			}
			set
			{
				if ((this._FoodPlanItemID != value))
				{
					if (this._FoodPlanItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodPlanItemIDChanging(value);
					this.SendPropertyChanging();
					this._FoodPlanItemID = value;
					this.SendPropertyChanged("FoodPlanItemID");
					this.OnFoodPlanItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeID", DbType="BigInt NOT NULL")]
		public long RecipeID
		{
			get
			{
				return this._RecipeID;
			}
			set
			{
				if ((this._RecipeID != value))
				{
					if (this._Recipe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRecipeIDChanging(value);
					this.SendPropertyChanging();
					this._RecipeID = value;
					this.SendPropertyChanged("RecipeID");
					this.OnRecipeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeIngredientID", DbType="BigInt NOT NULL")]
		public long RecipeIngredientID
		{
			get
			{
				return this._RecipeIngredientID;
			}
			set
			{
				if ((this._RecipeIngredientID != value))
				{
					if (this._RecipeIngredient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRecipeIngredientIDChanging(value);
					this.SendPropertyChanging();
					this._RecipeIngredientID = value;
					this.SendPropertyChanged("RecipeIngredientID");
					this.OnRecipeIngredientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientID", DbType="BigInt NOT NULL")]
		public long IngredientID
		{
			get
			{
				return this._IngredientID;
			}
			set
			{
				if ((this._IngredientID != value))
				{
					if (this._Ingredient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIngredientIDChanging(value);
					this.SendPropertyChanging();
					this._IngredientID = value;
					this.SendPropertyChanged("IngredientID");
					this.OnIngredientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetUnitQuantity", DbType="Float")]
		public System.Nullable<double> TargetUnitQuantity
		{
			get
			{
				return this._TargetUnitQuantity;
			}
			set
			{
				if ((this._TargetUnitQuantity != value))
				{
					this.OnTargetUnitQuantityChanging(value);
					this.SendPropertyChanging();
					this._TargetUnitQuantity = value;
					this.SendPropertyChanged("TargetUnitQuantity");
					this.OnTargetUnitQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodPlanItem_ShoppingListItem", Storage="_FoodPlanItem", ThisKey="FoodPlanItemID", OtherKey="Id", IsForeignKey=true)]
		public FoodPlanItem FoodPlanItem
		{
			get
			{
				return this._FoodPlanItem.Entity;
			}
			set
			{
				FoodPlanItem previousValue = this._FoodPlanItem.Entity;
				if (((previousValue != value) 
							|| (this._FoodPlanItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FoodPlanItem.Entity = null;
						previousValue.ShoppingListItems.Remove(this);
					}
					this._FoodPlanItem.Entity = value;
					if ((value != null))
					{
						value.ShoppingListItems.Add(this);
						this._FoodPlanItemID = value.Id;
					}
					else
					{
						this._FoodPlanItemID = default(long);
					}
					this.SendPropertyChanged("FoodPlanItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_ShoppingListItem", Storage="_Ingredient", ThisKey="IngredientID", OtherKey="Id", IsForeignKey=true)]
		public Ingredient Ingredient
		{
			get
			{
				return this._Ingredient.Entity;
			}
			set
			{
				Ingredient previousValue = this._Ingredient.Entity;
				if (((previousValue != value) 
							|| (this._Ingredient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ingredient.Entity = null;
						previousValue.ShoppingListItems.Remove(this);
					}
					this._Ingredient.Entity = value;
					if ((value != null))
					{
						value.ShoppingListItems.Add(this);
						this._IngredientID = value.Id;
					}
					else
					{
						this._IngredientID = default(long);
					}
					this.SendPropertyChanged("Ingredient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RecipeIngredient_ShoppingListItem", Storage="_RecipeIngredient", ThisKey="RecipeIngredientID", OtherKey="Id", IsForeignKey=true)]
		public RecipeIngredient RecipeIngredient
		{
			get
			{
				return this._RecipeIngredient.Entity;
			}
			set
			{
				RecipeIngredient previousValue = this._RecipeIngredient.Entity;
				if (((previousValue != value) 
							|| (this._RecipeIngredient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RecipeIngredient.Entity = null;
						previousValue.ShoppingListItems.Remove(this);
					}
					this._RecipeIngredient.Entity = value;
					if ((value != null))
					{
						value.ShoppingListItems.Add(this);
						this._RecipeIngredientID = value.Id;
					}
					else
					{
						this._RecipeIngredientID = default(long);
					}
					this.SendPropertyChanged("RecipeIngredient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recipe_ShoppingListItem", Storage="_Recipe", ThisKey="RecipeID", OtherKey="Id", IsForeignKey=true)]
		public Recipe Recipe
		{
			get
			{
				return this._Recipe.Entity;
			}
			set
			{
				Recipe previousValue = this._Recipe.Entity;
				if (((previousValue != value) 
							|| (this._Recipe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Recipe.Entity = null;
						previousValue.ShoppingListItems.Remove(this);
					}
					this._Recipe.Entity = value;
					if ((value != null))
					{
						value.ShoppingListItems.Add(this);
						this._RecipeID = value.Id;
					}
					else
					{
						this._RecipeID = default(long);
					}
					this.SendPropertyChanged("Recipe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShoppingList_ShoppingListItem", Storage="_ShoppingList", ThisKey="ShoppingListID", OtherKey="Id", IsForeignKey=true)]
		public ShoppingList ShoppingList
		{
			get
			{
				return this._ShoppingList.Entity;
			}
			set
			{
				ShoppingList previousValue = this._ShoppingList.Entity;
				if (((previousValue != value) 
							|| (this._ShoppingList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ShoppingList.Entity = null;
						previousValue.ShoppingListItems.Remove(this);
					}
					this._ShoppingList.Entity = value;
					if ((value != null))
					{
						value.ShoppingListItems.Add(this);
						this._ShoppingListID = value.Id;
					}
					else
					{
						this._ShoppingListID = default(long);
					}
					this.SendPropertyChanged("ShoppingList");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FoodPlans")]
	public partial class FoodPlan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private string _Description;
		
		private System.DateTime _StartDate;
		
		private System.Nullable<long> _Owner;
		
		private System.Nullable<double> _DefaultPortions;
		
		private EntitySet<FoodPlanItem> _FoodPlanItems;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnOwnerChanging(System.Nullable<long> value);
    partial void OnOwnerChanged();
    partial void OnDefaultPortionsChanging(System.Nullable<double> value);
    partial void OnDefaultPortionsChanged();
    #endregion
		
		public FoodPlan()
		{
			this._FoodPlanItems = new EntitySet<FoodPlanItem>(new Action<FoodPlanItem>(this.attach_FoodPlanItems), new Action<FoodPlanItem>(this.detach_FoodPlanItems));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner", DbType="BigInt")]
		public System.Nullable<long> Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOwnerChanging(value);
					this.SendPropertyChanging();
					this._Owner = value;
					this.SendPropertyChanged("Owner");
					this.OnOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultPortions", DbType="Float")]
		public System.Nullable<double> DefaultPortions
		{
			get
			{
				return this._DefaultPortions;
			}
			set
			{
				if ((this._DefaultPortions != value))
				{
					this.OnDefaultPortionsChanging(value);
					this.SendPropertyChanging();
					this._DefaultPortions = value;
					this.SendPropertyChanged("DefaultPortions");
					this.OnDefaultPortionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodPlan_FoodPlanItem", Storage="_FoodPlanItems", ThisKey="Id", OtherKey="FoodPlanID")]
		public EntitySet<FoodPlanItem> FoodPlanItems
		{
			get
			{
				return this._FoodPlanItems;
			}
			set
			{
				this._FoodPlanItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_FoodPlan", Storage="_User", ThisKey="Owner", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.FoodPlans.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.FoodPlans.Add(this);
						this._Owner = value.Id;
					}
					else
					{
						this._Owner = default(Nullable<long>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FoodPlanItems(FoodPlanItem entity)
		{
			this.SendPropertyChanging();
			entity.FoodPlan = this;
		}
		
		private void detach_FoodPlanItems(FoodPlanItem entity)
		{
			this.SendPropertyChanging();
			entity.FoodPlan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private string _eMail;
		
		private EntitySet<FoodPlan> _FoodPlans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    #endregion
		
		public User()
		{
			this._FoodPlans = new EntitySet<FoodPlan>(new Action<FoodPlan>(this.attach_FoodPlans), new Action<FoodPlan>(this.detach_FoodPlans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(50)")]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_FoodPlan", Storage="_FoodPlans", ThisKey="Id", OtherKey="Owner")]
		public EntitySet<FoodPlan> FoodPlans
		{
			get
			{
				return this._FoodPlans;
			}
			set
			{
				this._FoodPlans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FoodPlans(FoodPlan entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_FoodPlans(FoodPlan entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
}
#pragma warning restore 1591
